---
- hosts: all
  tasks: 
    - name: execute shell commands
      shell: uname
    - debug: msg="executing shell commands"
    - name: what changed
      shell: uname
      register: uname_result
    - debug: msg="{{uname_result}}"
    - debug: msg="{{uname_result, stdut_line}}"
    - debug: msg="{{uname_result, stdout}}"

