---
- name: Tagging modules
  hosts: all
  tasks:
   - name: installing tree
     apt:
       name: tree
       state: present
     tags:  tree_installation
   - name: installing apache
     apt:
       name: maven
       state: absent
     tags:  maven_installation
   - name: installing git
     apt:
       name: git
       state: present
...
