---
- name: debug method
  hosts: all
  tasks:
    - name: kernel
      debug: msg="{{ansible_kernel}}"
    - name: host name
      debug: msg="{{ansible_hostname}}"
    - debug: var=ansible_distribution
    - debug: var=hostvars

