---
- name: set up jenkins server
  hosts: jenkinsserver
  tasks:
    - name: install java, git, maven
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-8jdk, b: yes}
        - {a: git, b: no}
        - {a: maven, b: no}
    - name: download jenkins.war
      get_url:
        url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
        dest: /tmp
- name: setup tomcat on qa and prod server
  hosts: server
  tasks:
    - name: install tomcat8 and tomcat8-admin
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - { a: tomcat8, b: yes}
        - {a: tomcat8-admin, b: no}
    - name: copy tomcat-user.xml file
      copy:
         src: tomcat-users.xml
         dest: /etc/tomcat8


