---
- hosts: all
  tasks:
    - block:
        - name: Installing apache2
          apt:
            name: apache2
            state: present
      rescue:
        - name: install maven
          apt:
            name: nginx
            state: present
      always:
        - name: check url responce
          uri:
            url: "{{item}}"
            status_code: 200
            with_items:
                    - http://172.31.7.4 
